
name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest # Sets or specifies the runner 
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python # Sets up our python environment 
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install Dependencies # Installs any packages 
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirments.txt -t lambda/

    - name: Configure AWS Creds # Sets up AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secreats.AWS_ACCESS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Function # Zips lambda directory and updates lambda function 
      run: |
        cd lambda
        zip -r lamda.zip .
        aws lambda update-function-code --function-name  my-test-cicd-lambda --zip-file fileb://lambda.zip
